inherit_from:
  - https://shopify.github.io/ruby-style-guide/rubocop.yml

AllCops:
  TargetRubyVersion: 2.4

Layout/RescueEnsureAlignment:
  Enabled: false # Reenable once https://github.com/rubocop-hq/rubocop/issues/6918 is fixed
